### ISSUE TITLE
Feature request PC shutdown add option Exit NINA

### ISSUE THREAD

**Issue by ACMBakx** [daleghent/nina-shutdown-pc#2]
In case of a prolongued power failure, the UPS eventually will shut down the computer in my dome.
What will happen if NINA is still running at that moment?
I do not want the computer to be shut down by NINA as other processes need to be terminated by a script running from my Dragonfly.
It would be really usefull if the option "Exit NINA" is added to the PC Shutdown plugin.
Then I can be confident that NINA will be closed properly. Or "Gracefully" as some people say , without the risk of corrupting files.
A "IM Taskkill nina.exe /F" is not desireable obviously.

**Comment by daleghent** [comment]
This plugin, succinctly named "Shutdown PC", would not be the place for such an instruction. If it closed NINA, it would not be able to also shutdown the PC because the NINA and this plugin would no longer be running. I'm not even sure that plugins have access to NINA's internal app closure routines anyhow.

As for running scripts when your UPS goes on battery power, you are looking for the wrong solution. What you should consider is doing a proper ASCOM safety device loop using Nicolàs de Hilster's [Generic UPS ASCOM driver](https://www.dehilster.info/astronomy/ascom_generic_ups_driver.php). If you have not already done this, there are examples pinned in NINA's #sequencer2-discussion channel regarding integrating a safety device into your sequences. This would allow you to automatically close the roof/shutter if the UPS went on-batter, as well as run whichever scripts you need ran in such a situation.

**Comment by ACMBakx** [comment]
Thank you Dale.Point taken. I shall investigate that route.Nicolàs is a very good friend of mine. I did a lot of testing for actually this piece of software, when he developped it. We were both on SGP back then. Now we are both migrated to NINA.The Cyberpower ups he mentions that is was tested on is mine. 😀Best regardsArieVerstuurd vanaf mijn iPadOp 7 jun 2024 om 21:22 heeft Dale Ghent ***@***.***> het volgende geschreven:﻿
Closed #2 as completed.
